services:
    n8n:
        image: n8nio/n8n:latest
        restart: unless-stopped
        ports:
            - '5678:5678'
        environment:
            - TZ=Asia/Tokyo
            - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
            - N8N_SECURE_COOKIE=false
        volumes:
            - n8n-data:/home/node/.n8n
            - ../workflow_template:/home/node/.n8n/workflow_template
            - ../backup/workflow:/home/node/.n8n/backup/workflow
            - ../backup/credential:/home/node/.n8n/backup/credential
volumes:
    n8n-data:
        driver: local